_target_: datamodule.datasets.aihub_multimodal.AIHubMultimodalDataset
data_dir: ${project_root}/assets/aihub/2019-01-005.멀티모달영상_sample/원천데이터
label_dir: ${project_root}/assets/aihub/2019-01-005.멀티모달영상_sample/라벨데이터
data_extension: mp4
label_extension: json
label_prefix: clip_
start_video_sec: 0.0
end_video_sec: 40
video_chunk_sec: 2
fps: 2
video_resize_rate: 0.05
require_label: false